version: '3.8'
services:
  postgis:
    image: 'postgis/postgis:latest'
    container_name: postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '54326:5432'
    volumes:
      - 'leakmited-postgis-data:/var/lib/postgresql/data'
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '54325:80'
    depends_on:
      - postgis
volumes:
  leakmited-postgis-data:
